import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { Inter } from "next/font/google";

import Layout from "@/components/Layout";
import profilePic from "../../public/images/profile/developer-pic.png";
import AnimatedText from "@/components/AnimatedText";
import { LinkArrow } from "@/components/Icons";
import HireMe from "@/components/HireMe";
import TransitionEffect from "@/components/TransitionEffect";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ toggleContact }) {
  return (
    <>
      <Head>
        <title>Jaron S | Home Page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      {/* <TransitionEffect /> */}
      <main className="flex items-center w-full min-h-screen">
        <Layout className="pt-0 lg:p-8 lg:-mt-20">
          <div className="flex items-center justify-between w-full lg:flex-col lg:justify-center">
            <div className="w-1/2 lg:w-full flex justify-center lg:pt-10">
              <Image
                src={profilePic}
                alt="Jaron Schoorlemmer"
                className="w-full h-auto lg:max-w-xs lg:w-full"
                priority
                sizes="(max-width: 768) 100vw,
                (max-width: 1200px) 50vw,
                50vw"
              />
            </div>
            <div className="w-1/2 flex flex-col items-center self-center lg:w-full">
              <AnimatedText
                text="Bridging the Gap Between Design & Functionality."
                className="!text-6xl !text-left xl:!text-5xl lg:!text-6xl md:!text-5xl sm:!text-3xl"
              />
              <p className="my-4 text-base font-medium md:text-sm">
                {
                  "As a skilled full-stack developer, I transform ideas into innovative, high-performing web and mobile solutions. Explore my portfolio to see my expertise in React, Next.js, Flutter and back-end technologies in action. Let's create something exceptional together."
                }
              </p>
              <div className="flex items-center self-start mt-2">
                <Link
                  href="/Resume.pdf"
                  target={"_blank"}
                  className="flex items-center md:p-2 md:px-4 md:text-base bg-dark text-light dark:bg-light dark:text-dark p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark hover:dark:bg-dark hover:dark:text-light hover:dark:border-light"
                  download={true}
                >
                  Resume <LinkArrow className={"w-6 ml-1"} />
                </Link>
                <button
                  className="ml-4 text-lg font-medium capitalize underline md:text-base"
                  onClick={toggleContact}
                >
                  Contact
                </button>
              </div>
            </div>
          </div>
        </Layout>
        <HireMe />
      </main>
    </>
  );
}
